---
  pkgs:
    - gcc
    - git
    - python-virtualenv

  pip_executable: pip2

  hpfeeds_logger_dir: /opt

  hpfeeds_repo: https://github.com/CommunityHoneyNetwork/hpfeeds.git
  ### NEED TO UPDATE THIS TO MASTER
  ### ONCE MASTER HAS THE FORK MERGED
  hpfeeds_version: master
  hpfeeds_dir: /srv